removed the bugs 🐞
randyhub-live/randyhub-live.github.io pull request #6
Opened 2020-06-09 06:29 UTC by Arunscape

:100: :heavy_check_mark:

2020-06-09 18:12 UTC, aagavin requested changes
keep bugs, plz

2020-06-09 18:13 UTC, reallynewbie commented
I agree with keeping the bugs

2020-06-09 18:17 UTC, Arunscape commented
Ah, I'll add the bugs back in then

2020-06-11 20:58 UTC, aagavin requested changes

2020-06-11 20:58 UTC, aagavin commented on covid/index.css
> +}
nit: new line at end of file

2020-06-11 20:58 UTC, aagavin commented on cookingwithrandy.html
> +</html>
nit: new line at end of file

2020-06-11 20:58 UTC, aagavin commented on styles/cooking.css
> +}
nit: new line at end of file

2020-06-11 20:58 UTC, aagavin commented on styles/style.css
> +}
nit: new line at end of file

2020-06-12 00:46 UTC, aagavin approved these changes

2020-06-12 01:04 UTC, Arunscape commented
@reallynewbie looks like this is ready to merge

2020-06-12 02:49 UTC, merged